### ISSUE TITLE
Error 1 linea 13

### ISSUE THREAD

**Issue by JaviEpi** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-manuelbg7#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-manuelbg7/blob/07fbd767fe22a2b835c33d2994f4db00dba7f5f7/ejemplo.html#L13
Manuel, donde tienes puesto Error 1, deberías de ponerlo en una etiqueta, por 
ejemplo: `<p>Error 1</p>`

**Comment by manuelbg7** [comment]
Error #1 corregido.
